searches = [
    "alabama school district",
    "alaska school district",
    "arizona school district",
    "arkansas school district",
    "california school district",
    "colorado school district",
    "connecticut school district",
    "delaware school district",
    "florida school district",
    "georgia school district",
    "hawaii school district",
    "idaho school district",
    "illinois school district",
    "indiana school district",
    "iowa school district",
    "kansas school district",
    "kentucky school district",
    "louisiana school district",
    "maine school district",
    "maryland school district",
    "massachusetts school district",
    "michigan school district",
    "minnesota school district",
    "mississippi school district",
    "missouri school district",
    "montana school district",
    "nebraska school district",
    "nevada school district",
    "new hampshire school district",
    "new jersey school district",
    "new mexico school district",
    "new york school district",
    "north carolina school district",
    "north dakota school district",
    "ohio school district",
    "oklahoma school district",
    "oregon school district",
    "pennsylvania school district",
    "rhode island school district",
    "south carolina school district",
    "south dakota school district",
    "tennessee school district",
    "texas school district",
    "utah school district",
    "vermont school district",
    "virginia school district",
    "washington school district",
    "west virginia school district",
    "wisconsin school district",
    "wyoming school district",
    '"high school"',
    '"school district"',
    '"elementary school"',
    '"unified school district"',
    '"union school district"',
    '"middle school"',
    '"public schools"',
    '"independent school district"'
]